[package]
name = "collections-ext"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "red black tree operations"
path = "tree/rbtree/ops"
harness = false

[dependencies]
