[package]
name = "collections-ext"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "red_black_tree_operations"
path = "benches/tree/redblack/ops.rs"
harness = false

[dependencies]
